-- CrowdSec bouncer — handler for generated server blocks (MEG-22).
--
-- Rendered as `access_by_lua_file` into proxy-host servers, and as
-- `server_rewrite_by_lua_file` into servers that answer with `return`
-- (redirection hosts, 404 hosts, default-TLS sites, a proxy host's Force-SSL
-- :80 server): `return` runs in the rewrite phase, before access, so an
-- access-phase check there would never run.
--
-- AppSec is global while APPSEC_URL is set: `Allow()` inspects every request
-- on every enforcing server, and the per-host `crowdsec_appsec_enabled` flag
-- (`$megoopm_crowdsec_appsec`) is a reserved marker. See docs/crowdsec.md.
--
-- The check itself — and why it fails open — is megoopm_crowdsec_check.lua.
require("megoopm_crowdsec_check").check()
