#!/bin/sh
# Entrypoint for the CrowdSec-enabled managed nginx proxy (MEG-22).
#
# Renders the bouncer config from the environment (so the LAPI URL / bouncer key
# / AppSec URL are never baked into the image), then execs nginx (OpenResty).
set -eu

: "${CROWDSEC_LAPI_URL:=http://crowdsec:8080}"
: "${CROWDSEC_APPSEC_URL:=http://crowdsec:7422}"
: "${CROWDSEC_BOUNCER_KEY:=}"

if [ -z "${CROWDSEC_BOUNCER_KEY}" ]; then
    echo "[megoopm] WARNING: CROWDSEC_BOUNCER_KEY is empty — the bouncer will" \
         "fail to authenticate to LAPI. Register one with 'cscli bouncers add'." >&2
fi

export CROWDSEC_LAPI_URL CROWDSEC_APPSEC_URL CROWDSEC_BOUNCER_KEY
envsubst '${CROWDSEC_LAPI_URL} ${CROWDSEC_APPSEC_URL} ${CROWDSEC_BOUNCER_KEY}' \
    < /etc/nginx/crowdsec-bouncer.conf.template \
    > /etc/nginx/crowdsec-bouncer.conf

# --- Logging + client IP (/etc/nginx/logging.conf, included from nginx.conf) ---
# * Always keep the container's stdout/stderr logs.
# * CROWDSEC_SYSLOG_ADDR (host:port, UDP): also ship access + error logs to the
#   CrowdSec agent's syslog acquisition, so its nginx scenarios (probing, bad
#   user agents, brute force, ...) detect attackers and ban them at the edge.
# * NGINX_REAL_IP_HEADER + NGINX_REAL_IP_FROM: behind a CDN/tunnel/LB the
#   client address is in a header (Cloudflare: CF-Connecting-IP). Trusting it
#   from the listed proxy CIDRs makes logs AND the bouncer see the real client
#   instead of the proxy — otherwise a detection would ban the proxy itself.
: "${CROWDSEC_SYSLOG_ADDR:=}"
: "${NGINX_REAL_IP_HEADER:=}"
: "${NGINX_REAL_IP_FROM:=}"
{
    echo "# Generated by docker-entrypoint.sh from the environment — do not edit."
    echo "access_log /usr/local/openresty/nginx/logs/access.log combined;"
    echo "error_log /usr/local/openresty/nginx/logs/error.log warn;"
    if [ -n "${CROWDSEC_SYSLOG_ADDR}" ]; then
        echo "access_log syslog:server=${CROWDSEC_SYSLOG_ADDR},tag=nginx,severity=info combined;"
        echo "error_log syslog:server=${CROWDSEC_SYSLOG_ADDR},tag=nginx warn;"
    fi
    if [ -n "${NGINX_REAL_IP_HEADER}" ]; then
        for cidr in $(echo "${NGINX_REAL_IP_FROM}" | tr ',' ' '); do
            echo "set_real_ip_from ${cidr};"
        done
        echo "real_ip_header ${NGINX_REAL_IP_HEADER};"
        echo "real_ip_recursive on;"
    fi
} > /etc/nginx/logging.conf

# --- Visitor analytics (/etc/nginx/lua/megoopm_analytics_conf.lua) ---
# The log-phase handler needs Redis coordinates. A generated Lua file rather
# than a parsed .conf: nothing to tokenise, and a syntax error fails loudly at
# require() instead of silently disabling counting.
: "${REDIS_URL:=}"
: "${ANALYTICS_ENABLED:=true}"
_redis_hostport="$(echo "${REDIS_URL}" | sed -e 's|^redis://||' -e 's|^rediss://||' -e 's|/.*$||' -e 's|^.*@||')"
_redis_host="$(echo "${_redis_hostport}" | cut -d: -f1)"
_redis_port="$(echo "${_redis_hostport}" | cut -s -d: -f2)"
{
    echo "-- Generated by docker-entrypoint.sh -- do not edit."
    echo "return {"
    if [ -n "${_redis_host}" ] && [ "${ANALYTICS_ENABLED}" = "true" ]; then
        echo "  enabled = true,"
    else
        echo "  enabled = false,"
    fi
    echo "  host = \"${_redis_host:-redis}\","
    echo "  port = ${_redis_port:-6379},"
    echo "  prefix = \"megoopm:visits\","
    # Two days: long enough that a flush outage does not lose data, short
    # enough that a permanently-down flush cannot grow Redis without bound.
    echo "  ttl = 172800,"
    echo "  status_port = \"8081\","
    echo "}"
} > /etc/nginx/lua/megoopm_analytics_conf.lua

# --- Reload agent (worker <-> nginx control channel, socket-free) ---
# socat spawns /reload-agent.sh per connection on :9099 (never published, so
# only the compose network can reach it). Runs in a restart loop so a crashed
# socat comes back within a second; the container healthcheck pings it.
: "${NGINX_RELOAD_TOKEN:=}"
if [ -z "${NGINX_RELOAD_TOKEN}" ]; then
    echo "[megoopm] WARNING: NGINX_RELOAD_TOKEN is empty — the reload agent will" \
         "refuse every request, so the worker cannot validate/reload this nginx." >&2
fi
export NGINX_RELOAD_TOKEN
(
    while true; do
        socat TCP-LISTEN:9099,fork,reuseaddr EXEC:/reload-agent.sh
        sleep 1
    done
) &

exec "$@"
