"""Contract tests for the published OpenAPI document.

The backend *publishes* ``backend/openapi.json`` (generated by
``python -m scripts.export_openapi``); the frontend's ``npm run gen:api``
consumes it to produce TypeScript types. If the committed document drifts from
what the app actually serves, the generated frontend types silently go wrong —
so this gate fails CI until the file is regenerated and committed.
"""

from __future__ import annotations

import json

from httpx import AsyncClient
from scripts.export_openapi import OPENAPI_PATH, build_openapi_json


def test_committed_openapi_is_in_sync() -> None:
    """The committed contract must match the app's live schema."""
    assert OPENAPI_PATH.exists(), (
        "backend/openapi.json is missing. Generate it with "
        "`python -m scripts.export_openapi` and commit the result."
    )
    committed = OPENAPI_PATH.read_text(encoding="utf-8")
    assert committed == build_openapi_json(), (
        "backend/openapi.json is stale. Regenerate with "
        "`python -m scripts.export_openapi` and commit the result."
    )


def test_openapi_document_shape() -> None:
    """Basic invariants the frontend generator relies on."""
    schema = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    assert schema["openapi"].startswith("3."), schema["openapi"]
    assert schema["info"]["title"]
    assert "/health" in schema["paths"]


async def test_openapi_is_served_by_the_app(client: AsyncClient) -> None:
    """FastAPI serves the live document at ``/openapi.json``."""
    resp = await client.get("/openapi.json")
    assert resp.status_code == 200
    body = resp.json()
    assert body["openapi"].startswith("3.")
    assert body["info"]["title"]
