"""MEG-15 core domain model

Revision ID: 0002_core_domain
Revises: 0002_users
Create Date: 2026-08-26 21:04:48.827515
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_core_domain"
down_revision: str | None = "0002_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_lists",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("satisfy_any", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pass_auth", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_lists")),
    )
    op.create_table(
        "audit_log",
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column(
            "action",
            sa.Enum("create", "update", "delete", "enable", "disable", name="audit_action"),
            nullable=False,
        ),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_log_object", "audit_log", ["object_type", "object_id"], unique=False)
    op.create_table(
        "certificates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("letsencrypt", "custom", "self_signed", name="certificate_provider"),
            nullable=False,
        ),
        sa.Column(
            "domain_names",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("expires_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
    )
    op.create_table(
        "upstreams",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "lb_method",
            sa.Enum(
                "round_robin", "least_conn", "ip_hash", "hash", "random", name="load_balance_method"
            ),
            server_default="round_robin",
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upstreams")),
    )
    op.create_table(
        "access_list_auth",
        sa.Column("access_list_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["access_list_id"],
            ["access_lists.id"],
            name=op.f("fk_access_list_auth_access_list_id_access_lists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_list_auth")),
        sa.UniqueConstraint("access_list_id", "username", name="access_list_auth_username"),
    )
    op.create_index(
        op.f("ix_access_list_auth_access_list_id"),
        "access_list_auth",
        ["access_list_id"],
        unique=False,
    )
    op.create_table(
        "access_list_clients",
        sa.Column("access_list_id", sa.BigInteger(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column(
            "directive", sa.Enum("allow", "deny", name="access_list_directive"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["access_list_id"],
            ["access_lists.id"],
            name=op.f("fk_access_list_clients_access_list_id_access_lists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_list_clients")),
    )
    op.create_index(
        op.f("ix_access_list_clients_access_list_id"),
        "access_list_clients",
        ["access_list_id"],
        unique=False,
    )
    op.create_table(
        "dead_hosts",
        sa.Column(
            "domain_names",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("certificate_id", sa.BigInteger(), nullable=True),
        sa.Column("ssl_forced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("http2_support", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_subdomains", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("advanced_config", sa.Text(), server_default="", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_dead_hosts_certificate_id_certificates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_hosts")),
    )
    op.create_index(
        op.f("ix_dead_hosts_certificate_id"), "dead_hosts", ["certificate_id"], unique=False
    )
    op.create_table(
        "proxy_hosts",
        sa.Column(
            "domain_names",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("upstream_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "forward_scheme",
            sa.Enum("http", "https", name="http_scheme"),
            server_default="http",
            nullable=False,
        ),
        sa.Column("certificate_id", sa.BigInteger(), nullable=True),
        sa.Column("access_list_id", sa.BigInteger(), nullable=True),
        sa.Column("ssl_forced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("http2_support", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_subdomains", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("caching_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("block_exploits", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("allow_websocket_upgrade", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("advanced_config", sa.Text(), server_default="", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["access_list_id"],
            ["access_lists.id"],
            name=op.f("fk_proxy_hosts_access_list_id_access_lists"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_proxy_hosts_certificate_id_certificates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["upstream_id"],
            ["upstreams.id"],
            name=op.f("fk_proxy_hosts_upstream_id_upstreams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxy_hosts")),
    )
    op.create_index(
        op.f("ix_proxy_hosts_access_list_id"), "proxy_hosts", ["access_list_id"], unique=False
    )
    op.create_index(
        op.f("ix_proxy_hosts_certificate_id"), "proxy_hosts", ["certificate_id"], unique=False
    )
    op.create_index(
        op.f("ix_proxy_hosts_upstream_id"), "proxy_hosts", ["upstream_id"], unique=False
    )
    op.create_table(
        "redirection_hosts",
        sa.Column(
            "domain_names",
            postgresql.ARRAY(sa.String(length=255)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "forward_scheme",
            sa.Enum("auto", "http", "https", name="redirect_scheme"),
            server_default="auto",
            nullable=False,
        ),
        sa.Column("forward_domain_name", sa.String(length=255), nullable=False),
        sa.Column("forward_http_code", sa.Integer(), server_default="302", nullable=False),
        sa.Column("preserve_path", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("certificate_id", sa.BigInteger(), nullable=True),
        sa.Column("ssl_forced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("http2_support", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hsts_subdomains", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("block_exploits", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("advanced_config", sa.Text(), server_default="", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "forward_http_code BETWEEN 300 AND 308",
            name=op.f("ck_redirection_hosts_forward_http_code_range"),
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_redirection_hosts_certificate_id_certificates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_redirection_hosts")),
    )
    op.create_index(
        op.f("ix_redirection_hosts_certificate_id"),
        "redirection_hosts",
        ["certificate_id"],
        unique=False,
    )
    op.create_table(
        "streams",
        sa.Column("incoming_port", sa.Integer(), nullable=False),
        sa.Column("forward_host", sa.String(length=255), nullable=False),
        sa.Column("forward_port", sa.Integer(), nullable=False),
        sa.Column("tcp_forwarding", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("udp_forwarding", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("certificate_id", sa.BigInteger(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "forward_port BETWEEN 1 AND 65535", name=op.f("ck_streams_forward_port_range")
        ),
        sa.CheckConstraint(
            "incoming_port BETWEEN 1 AND 65535", name=op.f("ck_streams_incoming_port_range")
        ),
        sa.CheckConstraint(
            "tcp_forwarding OR udp_forwarding", name=op.f("ck_streams_at_least_one_protocol")
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_streams_certificate_id_certificates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streams")),
        sa.UniqueConstraint("incoming_port", name=op.f("uq_streams_incoming_port")),
    )
    op.create_index(op.f("ix_streams_certificate_id"), "streams", ["certificate_id"], unique=False)
    op.create_table(
        "upstream_backends",
        sa.Column("upstream_id", sa.BigInteger(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), server_default="1", nullable=False),
        sa.Column("max_fails", sa.Integer(), server_default="1", nullable=False),
        sa.Column("fail_timeout_seconds", sa.Integer(), server_default="10", nullable=False),
        sa.Column("backup", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("down", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fail_timeout_seconds >= 0", name=op.f("ck_upstream_backends_fail_timeout_non_negative")
        ),
        sa.CheckConstraint(
            "max_fails >= 0", name=op.f("ck_upstream_backends_max_fails_non_negative")
        ),
        sa.CheckConstraint(
            "port BETWEEN 1 AND 65535", name=op.f("ck_upstream_backends_port_range")
        ),
        sa.CheckConstraint("weight >= 0", name=op.f("ck_upstream_backends_weight_non_negative")),
        sa.ForeignKeyConstraint(
            ["upstream_id"],
            ["upstreams.id"],
            name=op.f("fk_upstream_backends_upstream_id_upstreams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upstream_backends")),
        sa.UniqueConstraint("upstream_id", "host", "port", name="upstream_backends_host_port"),
    )
    op.create_index(
        op.f("ix_upstream_backends_upstream_id"), "upstream_backends", ["upstream_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upstream_backends_upstream_id"), table_name="upstream_backends")
    op.drop_table("upstream_backends")
    op.drop_index(op.f("ix_streams_certificate_id"), table_name="streams")
    op.drop_table("streams")
    op.drop_index(op.f("ix_redirection_hosts_certificate_id"), table_name="redirection_hosts")
    op.drop_table("redirection_hosts")
    op.drop_index(op.f("ix_proxy_hosts_upstream_id"), table_name="proxy_hosts")
    op.drop_index(op.f("ix_proxy_hosts_certificate_id"), table_name="proxy_hosts")
    op.drop_index(op.f("ix_proxy_hosts_access_list_id"), table_name="proxy_hosts")
    op.drop_table("proxy_hosts")
    op.drop_index(op.f("ix_dead_hosts_certificate_id"), table_name="dead_hosts")
    op.drop_table("dead_hosts")
    op.drop_index(op.f("ix_access_list_clients_access_list_id"), table_name="access_list_clients")
    op.drop_table("access_list_clients")
    op.drop_index(op.f("ix_access_list_auth_access_list_id"), table_name="access_list_auth")
    op.drop_table("access_list_auth")
    op.drop_table("upstreams")
    op.drop_table("certificates")
    op.drop_index("ix_audit_log_object", table_name="audit_log")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("access_lists")
    # ### end Alembic commands ###

    # Native Postgres ENUM types are created implicitly by create_table but are
    # NOT dropped by drop_table — remove them explicitly so a re-upgrade does not
    # fail with "type already exists".
    for enum_name in (
        "audit_action",
        "certificate_provider",
        "load_balance_method",
        "http_scheme",
        "redirect_scheme",
        "access_list_directive",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
